### ISSUE TITLE
Unnecessary include of entity framework in nuget package

### ISSUE THREAD

**Issue by antidemon** [scottksmith95/LINQKit#26]
As far as I can see from the source download from http://www.albahari.com/nutshell/LinqKitSource.zip there is no need for the nuget package to include entity framework apart from for the demo project. Can we remove this dependency from the nuget package please.

**Comment by Thorium** [comment]
Source code on www.albahari.com is quite old. Since then we had to support async queries. And for that we need the interfaces from EF: 
IDbAsyncEnumerator<T> and IDbAsyncEnumerable<T>

So after this commit there has been this dependency:
https://github.com/scottksmith95/LINQKit/commit/890bccc370f13578588c8b5b2fb4c3a83bab1294

The old .NET 3.5 version actually wouldn't need EF, so this could be removed from the LinqKit.Net35 solution. #18

**Comment by Thorium** [comment]
Now you can get also the 3.5 version from the NuGet package, from version LinqKit 1.1.3
